platform :ios, '9.0'

target 'FMListPlaceholderExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'MJRefresh', '~> 3.1.15.7'
pod 'FMListPlaceholder', :path => './../'

end
